create table users_tokens
(
    id                bigint generated by default as identity
        primary key,
    access            varchar(255) not null
        constraint uk_lfqo34ae0ua8qm9glaf88nifn
            unique,
    refresh           varchar(255) not null
        constraint uk_ijfoauv75em0qe4vrugr7u39t
            unique,
    users_id          bigint       not null
        constraint fkejn492kbahdsfgpoou10beuoh
            references users,
    expires_date_time timestamp,
    created_date_time timestamp
);