version: '3.4'

services:
  db:
    image: postgres:12.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookstore
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - '6379:6379'